---
- name: Copy K3s binary to master node
  copy:
    src: k3s
    dest: /usr/local/bin/k3s
    mode: "0755"

- name: Copy K3s airgap images to master node
  copy:
    src: k3s-airgap-images-amd64.tar
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar

- name: Install K3s master node
  shell: |
    INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" /usr/local/bin/k3s server
  args:
    creates: /etc/rancher/k3s/k3s.yaml

- name: Wait for K3s master node to be ready
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 300
