---
# Main playbook for setting up K3s master node offline

# Step 1: Ensure directory for K3s airgap images exists
# This ensures that the directory for the airgap images is created before copying.
- name: Ensure directory for K3s airgap images exists
  file:
    path: /var/lib/rancher/k3s/agent/images/
    state: directory
    mode: "0755"

# Step 2: Copy the K3s binary to the master node
- name: Copy K3s binary to master node
  copy:
    src: k3s
    dest: /usr/local/bin/k3s
    mode: "0755"

# Step 3: Copy K3s airgap images to master node
- name: Copy K3s airgap images to master node
  copy:
    src: k3s-airgap-images-amd64.tar
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar

# Step 4: Install K3s master node
# The INSTALL_K3S_SKIP_DOWNLOAD flag ensures the script doesn't download anything, since we copied the binary locally.
- name: Install K3s master node
  shell: |
    INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" /usr/local/bin/k3s server
  args:
    creates: /etc/rancher/k3s/k3s.yaml

# Step 5: Wait for K3s master node to be ready
# This ensures the master node is fully operational by waiting for the kubeconfig file.
- name: Wait for K3s master node to be ready
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 300
