---
- name: Copy K3s binary to agent node
  copy:
    src: k3s
    dest: /usr/local/bin/k3s
    mode: "0755"

- name: Copy K3s airgap images to agent node
  copy:
    src: k3s-airgap-images-amd64.tar
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar

- name: Install K3s agent node
  shell: |
    INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ k3s_token }} /usr/local/bin/k3s agent
  args:
    creates: /var/lib/rancher/k3s/agent/kubelet.pid
